services:
  
  frontapp:
    image: frontapp
    #build: ./frontapp/
    #  context: .
    #  dockerfile: ./Dockerfile
    ports:
    - 8080:8080
    environment:
    - BACK_URL=backapp:8080
  
  backapp:
    image: backapp
    #build: ./backapp/
    #  context: .
    #  dockerfile: ./Dockerfile
    #ports:
    #- 8081:8080
    