apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw3.fullname" . }}-backapp
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
    homework: backapp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hw3.selectorLabels" . | nindent 6 }}
      homework: backapp
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hw3.selectorLabels" . | nindent 8 }}
        homework: backapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: APP_DEFAULT_MESSAGE
            value: backapp
          - name: JAVA_OPTS
            value: 
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backapp.image.repository }}:{{ .Values.backapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
