apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw3.fullname" . }}-backapp
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
    homework: backapp
spec:
  ports:
    - port: {{ .Values.backapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hw3.selectorLabels" . | nindent 4 }}
    homework: backapp
