apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw3.fullname" . }}-frontapp
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
    homework: frontapp
spec:
  ports:
    - port: {{ .Values.frontapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hw3.selectorLabels" . | nindent 4 }}
    homework: frontapp
