apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw3.fullname" . }}-frontapp
  labels:
    {{- include "hw3.labels" . | nindent 4 }}
    homework: frontapp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hw3.selectorLabels" . | nindent 6 }}
      homework: frontapp
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hw3.selectorLabels" . | nindent 8 }}
        homework: frontapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: BACK_URL
            value: http://backapp:8080
          - name: APP_DEFAULT_MESSAGE
            value: frontapp
          - name: JAVA_OPTS
            value: 
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontapp.image.repository }}:{{ .Values.frontapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
